-- ================================================================
-- alerts_schema.sql
-- Add this table to your existing Supabase database.
-- Run this in the Supabase SQL Editor ONCE.
-- ================================================================


-- ----------------------------------------------------------------
-- TABLE: alerts
-- Stores every alert generated by the monitoring system.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alerts (
    alert_id        BIGSERIAL       PRIMARY KEY,
    asset_id        INT             REFERENCES assets(asset_id) ON DELETE SET NULL,

    -- Alert Classification
    alert_type      VARCHAR(50)     NOT NULL,
    -- 'NEW_ASSET'       → a new device appeared in the inventory
    -- 'REMOVED_ASSET'   → a device disappeared from the inventory
    -- 'STATUS_CHANGE'   → asset status field changed (active → inactive, etc.)
    -- 'CRITICALITY_CHANGE' → criticality was raised or lowered
    -- 'IP_CHANGE'       → IP address changed (could be unauthorized)
    -- 'OS_CHANGE'       → operating system changed
    -- 'OWNER_CHANGE'    → asset ownership changed

    severity        VARCHAR(10)     NOT NULL DEFAULT 'INFO',
    -- 'INFO'    → routine change, no action needed
    -- 'WARNING' → notable change, should be reviewed
    -- 'CRITICAL' → high-risk change, action required immediately

    -- Content
    asset_name      VARCHAR(150),           -- denormalized for quick display
    message         TEXT            NOT NULL, -- human-readable description
    details         JSONB           DEFAULT '{}',
    -- {"field": "status", "old_value": "active", "new_value": "inactive"}

    -- Status
    is_acknowledged BOOLEAN         DEFAULT FALSE,  -- has a human seen this?
    acknowledged_by VARCHAR(100),
    acknowledged_at TIMESTAMP,

    -- Monitoring run this alert came from
    monitoring_run_id VARCHAR(50),          -- UUID of the monitor.py run

    -- Timing
    created_at      TIMESTAMP       DEFAULT NOW()
);


-- ----------------------------------------------------------------
-- TABLE: monitoring_runs
-- One record per execution of monitor.py — the "heartbeat" log.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS monitoring_runs (
    run_id              VARCHAR(50)     PRIMARY KEY,   -- UUID
    run_started_at      TIMESTAMP       DEFAULT NOW(),
    run_finished_at     TIMESTAMP,
    duration_seconds    DECIMAL(6,2),

    -- Snapshot counts
    previous_asset_count INT            DEFAULT 0,
    current_asset_count  INT            DEFAULT 0,

    -- Change summary
    total_added         INT             DEFAULT 0,
    total_removed       INT             DEFAULT 0,
    total_modified      INT             DEFAULT 0,
    total_unchanged     INT             DEFAULT 0,

    -- Alert summary
    total_alerts        INT             DEFAULT 0,
    critical_alerts     INT             DEFAULT 0,
    warning_alerts      INT             DEFAULT 0,
    info_alerts         INT             DEFAULT 0,

    status              VARCHAR(20)     DEFAULT 'completed',
    -- 'running' | 'completed' | 'failed'
    error_message       TEXT,
    notes               TEXT
);


-- Indexes for fast querying
CREATE INDEX IF NOT EXISTS idx_alerts_asset_id    ON alerts(asset_id);
CREATE INDEX IF NOT EXISTS idx_alerts_severity    ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_type        ON alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at  ON alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_ack         ON alerts(is_acknowledged);
CREATE INDEX IF NOT EXISTS idx_alerts_run_id      ON alerts(monitoring_run_id);

-- ================================================================
-- Done! New tables added:
--   alerts          → every alert generated by the monitor
--   monitoring_runs → log of each monitoring execution
-- ================================================================
